kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sormas-operator
subjects:
- kind: ServiceAccount
  name: sormas-operator
  namespace: nka
roleRef:
  kind: ClusterRole
  name: sormas-operator
  apiGroup: rbac.authorization.k8s.io
